PROGRAM = main
CC = g++
CFLAGS = -O2
HEADER = ../functions.hpp ../inputs.hpp 

ALL : initializeParticlePositionAndVelocity_for2dim

initializeParticlePositionAndVelocity_for2dim : initializeParticlePositionAndVelocity_for2dim.cpp 
	$(CC) $(CFLAGS) -o initializeParticlePositionAndVelocity_for2dim.o initializeParticlePositionAndVelocity_for2dim.cpp $(HEADER)